apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration
  namespace: gittix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata: 
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image:  imtejesh95/expiration:latest
          env:      
            - name: NATS_URL
              value: "http://nats-svc:4222" 
            - name: NATS_CLUSTER_ID
              value: "ticketing" 
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name                                             
            - name: REDIS_HOST
              value: expiration-redis-svc
