apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: gittix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata: 
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image:  imtejesh95/orders:latest
          env:
            - name: ORDER_EXP_WINDOW_SECS
              value: '120'             
            - name: MONGO_URI
              value: "mongodb://orders-mongo-svc:27017/orders"        
            - name: NATS_URL
              value: "http://nats-svc:4222" 
            - name: NATS_CLUSTER_ID
              value: "ticketing" 
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name                                             
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: orders-svc
  namespace: gittix
spec:
  selector:
    app: orders
  ports:
    - name: orders
      protocol: TCP
      port: 3000
      targetPort: 3000

