apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: gittix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata: 
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image:  imtejesh95/payments:latest
          env:
            - name: STRIPE_SUCCESS_URL
              value: https://gittix.dev/orders/payment-success
            - name: STRIPE_CANCEL_URL
              value: https://gittix.dev/orders/payment-failure                      
            - name: MONGO_URI
              value: "mongodb://payments-mongo-svc:27017/payments"        
            - name: NATS_URL
              value: "http://nats-svc:4222" 
            - name: NATS_CLUSTER_ID
              value: "ticketing" 
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name                                             
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: payments-svc
  namespace: gittix
spec:
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000

