name: deploy-expiration

on:
  push:
    branches:
      - "main"
    paths:
      - "expiration/**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: cd expiration && docker build -t imtejesh95/expiration .

      - name: Docker Login
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Push Docker Image
        run: docker push imtejesh95/expiration       

      - name: Install doctl 
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}   

      - name: Kubernetes Cluster Config
        run: doctl kubernetes cluster kubeconfig save gittix

      - name: Deployment Rolling Update 
        run: kubectl rollout restart deployment expiration
