# This is a basic workflow to help you get started with Actions

name: tests

# Controls when the workflow will run
on:
  pull_request
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install
        run: cd auth && npm install 
      
      - name: tests
        run: npm test
